id: I38687F6A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:19:56+00:00'
last_modified: '2022-06-08T08:56:30.496717+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29037
  title: ལམ་རིམ་མཆན་བཞི་སྦྲགས་མ། ༼བླ་བྲང་བཀྲ་ཤིས་འཁྱིལ་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C2F:
      image_group_id: I5047
      title: ''
      total_pages: 978
      order: 1
      base_file: 4C2F.txt
    B4FB:
      image_group_id: I5048
      title: ''
      total_pages: 1002
      order: 2
      base_file: B4FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
